### ISSUE TITLE
chests doesn't accept input from hoppers

### ISSUE THREAD

**Issue by maIwina** [pop4959/Bolt#102]
what title says, if you use /bolt:unlock and unlock chest that chest won't accept input from hoppers it can be fixed with /bolt:unlock but you still have to take out items from that hopper for it to work again

**Comment by pop4959** [comment]
Not a bug. The locked container needs to have the correct permissions (through the deposit/withdrawal protection type) on it to be able to transfer to/from unlocked containers. I assume you are using private protections which do not grant any access by default to other players / containers. Obviously this is intentional as otherwise it would be extremely easy to steal from protected containers via siphoning through unlocked containers.

If you have any other questions about usage, please use the Bolt support channel on our [Discord server](https://discord.gg/PHpuzZS).
