### ISSUE TITLE
[Bug] Uppercases in protection type name make it not work

### ISSUE THREAD

**Issue by Dezaku** [pop4959/Bolt#144]
E.g when a protection type is written in camelCase, whenever you try to modify a block and add that protection type you get told that the protection type doesn't exist.

**Comment by pop4959** [comment]
Sorry for the delay. Fixed in 251106e31320048637884db88636dcb3054849f8, the type key will now always be registered lowercase for the command. This makes the name case insensitive for all intents and purposes in the config and will no longer cause any issues.

If you want to have a custom display name for the protection type, you can do so by providing your own [custom translation file](https://github.com/pop4959/Bolt/wiki#translations).
