### ISSUE TITLE
[bug] Copper doors broken on 1.21

### ISSUE THREAD

**Issue by jarda09** [pop4959/Bolt#146]
If I use Right Click it does that:
[https://youtu.be/sZiirv-cnw0](https://youtu.be/sZiirv-cnw0)

**Comment by pop4959** [comment]
Normally Bolt doesn't need to add support for new doors (it uses the #doors tag) but for double opening, since these are new "iron doors" we'll need to update that piece. Currently Bolt assumes that iron doors are the only kind of door that cannot be opened by hand normally (which isn't true anymore, there's probably a new tag for this).

**Comment by jarda09** [comment]
I created own hotfix using this in Doors.java:

![image](https://github.com/user-attachments/assets/3f1329e0-cbb0-4a8f-af63-59b385bcfad8)
![image](https://github.com/user-attachments/assets/1f2a1e5b-354a-428b-9e16-c457353a249e)

**Comment by pop4959** [comment]
Apologies for the delay, I have been quite busy recently (which is why things have been slow on quite a few of my projects).

Fix looks good, I would probably look at using tags. If you are willing to make a pull request, I can merge it. Otherwise, I will try to take a look at this myself soon. Thanks!

**Comment by jarda09** [comment]
Ok, I created a pull request. 
[](https://github.com/pop4959/Bolt/pull/151)

In the end, I did it differently, using tags and added double openings with different oxidation of the copper doors.

**Comment by pop4959** [comment]
Fixed in 0b9b9b92c3ed4854a137dee52dade8db5ae80ccc
