### ISSUE TITLE
[Feature Request] Interactions with locked Iron Trapdoors

### ISSUE THREAD

**Issue by Velyn-N** [pop4959/Bolt#155]
Bolt already allows player to open/close locked Iron Doors just by interacting with them. However this does not apply to Iron Trapdoors.

As I can see no particular reason for this not being an option. LWC did support this too.
Therefore I propose to add this feature to Bolt.

**Comment by pop4959** [comment]
Can you check if this is already fixed in the latest versions on [CodeMC](https://ci.codemc.io/view/Author/job/pop4959/job/Bolt/) or [Github Actions](https://github.com/pop4959/Bolt/actions)? I'm fairly sure this was already fixed, although a release has not been made yet since then. I am planning to do another release soon, since 1.21.3 has just come out this week.

**Comment by Velyn-N** [comment]
I tested again with the most recent builds (Bolt from [this GH Actions Run](https://github.com/pop4959/Bolt/actions/runs/11267941715) and **Paper 1.21 Build 131** running on **Eclipse Adoptium Temurin-21.0.5+11**).

I configured Bolt to allow bare-hand opening of iron doors as shown in [the wiki](https://github.com/pop4959/Bolt/wiki#configuration) , apart from that just kept the default config:
```yaml
doors:
  open-iron: true
```
With this config value set I can open Iron Doors like normal wooden ones.

As this config only explicitly mentions doors I tried similar values for trapdoors:
```yaml
trapdoors:
  open-iron: true
```
However, this did not change any behaviour for trapdoors. Here is a short video of it not working:
![BoltDoors](https://github.com/user-attachments/assets/08f845a7-68d5-4e0f-b42a-229ebe1efa77)

If you need any further information I'll gladly help you out!

**Comment by jarda09** [comment]
I fixed it in Doors.java, using this
![image](https://github.com/user-attachments/assets/ce7409eb-3a83-4d24-8b6e-0995a52c91af)


jar:
[Bolt-1.1.26.jar.zip](https://github.com/user-attachments/files/17791445/Bolt-1.1.26.jar.zip)

**Comment by pop4959** [comment]
Apologies on the delay with this, super simple fix but I have been busy. Should be fixed in the latest.

@jarda09 Also in the future, please do not directly post links to jar files. I understand you are trying to help, but the correct approach here is to make a PR, and have the CI build a jar for you, for best security practices (since the integrity of the automatically built artifact can be verified more easily than some loose jar linked in a comment). Thank you.
