### ISSUE TITLE
Cannot getEntities asynchronously on Folia server

### ISSUE THREAD

**Issue by xiaoyueyoqwq** [pop4959/Bolt#53]
Logs: https://paste.ubuntu.com/p/BXtNQyTdtj/
ver: _This server is running Folia version git-Folia-"47105ea" (MC: 1.19.4) (Implementing API version 1.19.4-R0.1-SNAPSHOT) (Git: 47105ea)_

**Comment by pop4959** [comment]
I guess this is still an issue. Do you know if this seems to happen randomly for you as well, or is there a way you're able to consistently get this error to throw? Last time I tried I couldn't get it to happen.

**Comment by xiaoyueyoqwq** [comment]
> I guess this is still an issue. Do you know if this seems to happen randomly for you as well, or is there a way you're able to consistently get this error to throw? Last time I tried I couldn't get it to happen.

Quite simply, locking any block after using the /lock command will trigger this error, and I'm currently testing levers and note boxes

**Comment by pop4959** [comment]
I have an idea on how to fix this but I'm not sure how to do it yet with Folia.

Just wanted to let you know I am still actively looking for an appropriate fix for this. It's tricky since Bolt does really need access to these entities and cannot block the events.

**Comment by montlikadani** [comment]
Either way instead of using `getNearbyEntities` from `World` you could implement an alternative and temporary solution if you don't want to call nearbyEntities in sync. There is some old legacy code which can retrieve nearby entities. Also I found a related issue on Folia: https://github.com/PaperMC/Folia/issues/28 (see the answer)

_I actually have this old code [here](https://github.com/montlikadani/RageMode/blob/master/src/main/java/hu/montlikadani/ragemode/utils/Utils.java#L145-L172)_

**Comment by pop4959** [comment]
> Either way instead of using `getNearbyEntities` from `World` you could implement an alternative and temporary solution if you don't want to call nearbyEntities in sync. There is some old legacy code which can retrieve nearby entities. Also I found a related issue on Folia: [PaperMC/Folia#28](https://github.com/PaperMC/Folia/issues/28) (see the answer)
> 
> _I actually have this old code [here](https://github.com/montlikadani/RageMode/blob/master/src/main/java/hu/montlikadani/ragemode/utils/Utils.java#L145-L172)_

Yes, it looks like that is exactly the issue I was running into. Unfortunately the answer there does not help me because the events that Bolt listens to for protections may not involve a player, so there is no safe reference to call `getNearbyEntities` from. Getting the entities from the chunk may work, as I don't need a large radius around the protection (it's always either the same chunk or the neighbor chunk). I'll give it a try.

**Comment by xiaoyueyoqwq** [comment]
> > Either way instead of using `getNearbyEntities` from `World` you could implement an alternative and temporary solution if you don't want to call nearbyEntities in sync. There is some old legacy code which can retrieve nearby entities. Also I found a related issue on Folia: [PaperMC/Folia#28](https://github.com/PaperMC/Folia/issues/28) (see the answer)
> > _I actually have this old code [here](https://github.com/montlikadani/RageMode/blob/master/src/main/java/hu/montlikadani/ragemode/utils/Utils.java#L145-L172)_
> 
> Yes, it looks like that is exactly the issue I was running into. Unfortunately the answer there does not help me because the events that Bolt listens to for protections may not involve a player, so there is no safe reference to call `getNearbyEntities` from. Getting the entities from the chunk may work, as I don't need a large radius around the protection (it's always either the same chunk or the neighbor chunk). I'll give it a try.

okay, I think you fix it in build Bolt 1.0.484

**Comment by pop4959** [comment]
I didn't put in any fix yet so this will still be an issue.

**Comment by xiaoyueyoqwq** [comment]
> I didn't put in any fix yet so this will still be an issue.

okay, maybe I got a issue just now:
https://paste.ubuntu.com/p/PRPXcjN8Tw/

**Comment by pop4959** [comment]
Yes that is the same issue, just thrown from a different event. I'll update here when I get a chance to implement another fix.

**Comment by pop4959** [comment]
Fixed in 3a4581587dcf93be810787c0ef26ddd19a4f8307
