### ISSUE TITLE
Armorstands locked even to owner

### ISSUE THREAD

**Issue by BornToDoStuff** [pop4959/Bolt#69]
So far in my testing armorstands do successfully lock, but you can not put armor onto them, or take armor off of them, while they are locked.

To create this scenario I merely place an armorstand, type `/bolt lock` and it becomes a private armorstand, while locked I can not take off armor, or put armor onto, the armorstand. I have tested multiple protection types, but even as the owner this issue persists.
To fix the armorstand I unlock it and can interact with it normally again.

 Because the issue is solved by unlocking the armorstand, I believe it is likely Bolt.

**Comment by pop4959** [comment]
Going to close this, since it does not appear to be a bug on the latest version, at least in the way described in this issue. It's possible that you are running into another problem here but you will probably need to do further testing on your end to figure out what that is. Please make a new issue if you figure out what exactly causes this behavior for you, and it's something that still needs fixing in Bolt.
