### ISSUE TITLE
Half-Door on Break

### ISSUE THREAD

**Issue by Lorias-Jak** [pop4959/Bolt#86]
Im in creative and trying to destroy a locked door

git-Paper-117
Bolt-1.0.526

https://github.com/pop4959/Bolt/assets/62625225/348ea5dc-cac1-44ff-a8e4-28cdda89cadc

**Comment by pop4959** [comment]
Not able to reproduce this one, both sides break correctly. Might be another plugin causing it or a client-side bug / visual issue only because it looks like in chat it registers the block as unlocked correctly in Bolt when broken.

If you are able to provide steps to get this to happen on the latest version of Paper, with the vanilla client, and without other plugins, let me know and we can re-open this to take another look.
